[package]
name = "branchtransfer"
version = "0.1.0-DEV"
edition = "2024"

[[bin]]
name = "bxfer"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
git2 = "0.20.2"
rand = "0.9.1"
tempfile = "3.20.0"
